version = 1

test_patterns = [
  "tests/**",
  "**/test_*.py",
  "tests.py"
]

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"
type_checker = "mypy"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"
enabled = true
