# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

test_patterns = [
  "**/test_*.py",
  "tests.py",
  "tests/**"
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"
type_checker = "mypy"

[[analyzers]]
enabled = true
name = "test-coverage"
