# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

SPDX-PackageDownloadLocation = "https://weblate.org/"
SPDX-PackageName = "Weblate"
SPDX-PackageSupplier = "Michal Čihař <michal@weblate.org>"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = ["docs/**.html", "docs/**.png", "docs/**.webp", "docs/**.rst", "README.rst", "BACKERS.rst", "CONTACT.md", "CONTRIBUTING.md", "ci/README.rst", "dev-docker/README.rst", "weblate/static/security.txt"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"
path = "docs/schemas/**.json"
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = ["weblate/trans/tests/data/**", "weblate/trans/fixtures/simple-project.json", "weblate/billing/test-data/00000.pdf"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = ["weblate/templates/**", "weblate/wladmin/templates/**", "weblate/legal/templates/**"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = [".editorconfig", ".gitattributes", ".gitignore", ".gitmodules", ".imgbotconfig", ".pre-commit-config.yaml", ".pylintrc", ".readthedocs.yml", ".weblate", "MANIFEST.in", "codecov.yml", "pyproject.toml", "requirements**.txt", "dev-docker/environment", "scripts/yarn/.gitignore", "scripts/yarn/package.json", "scripts/yarn/yarn.lock", "setup.cfg", "docs/requirements.txt", "biome.json", "redocly.yaml", ".well-known/funding-manifest-urls", "uv.lock"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = ["weblate/static/widget-images/**.png", "weblate/static/weblate**.svg", "weblate/static/weblate**.png", "weblate/static/logo-**.png", "weblate/static/access/**.svg", "weblate/static/email-logo**.png", "weblate/static/favicon.ico", "docs/images/logo-text.svg"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = "weblate/static/auth/**.svg"
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Pictogrammers"
SPDX-License-Identifier = "Apache-2.0"
path = ["weblate/static/icons/**.svg", "weblate/static/state/**.svg", "weblate/static/sort/**.svg"]
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Copyright ©2017-2021, Clinton F. Goss"
SPDX-License-Identifier = "OFL-1.1"
path = "weblate/static/vendor/font-kurinto/**"
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Paul D. Hunt"
SPDX-License-Identifier = "OFL-1.1"
path = "weblate/static/js/vendor/fonts/**"
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Lea Verou"
SPDX-License-Identifier = "MIT"
path = "weblate/static/vendor/prism/**"
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = "client/package.json"
precedence = "aggregate"

[[annotations]]
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = "client/yarn.lock"
precedence = "aggregate"
