# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

##########
# WARNING!
# This docker-compose file is meant to be used in the development process
# and WILL perform very poorly in production.
#
# For production-ready docker-compose file see:
# https://github.com/WeblateOrg/docker-compose
#########

services:
  weblate:
    image: weblate-dev:latest
    build:
      context: ./weblate-dev/
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
    - ${WEBLATE_PORT}:8080
    user: $USER_ID:$GROUP_ID
    userns_mode: host
    tmpfs:
    - /app/cache:uid=$USER_ID,gid=$GROUP_ID
    - /tmp:uid=$USER_ID,gid=$GROUP_ID,exec
    - /run:uid=$USER_ID,gid=$GROUP_ID
    volumes:
      # Local data directory
    - $PWD/data:/app/data
      # Override Weblate with local dir
    - $PWD/..:/app/src
    restart: always
    depends_on:
    - database
    - cache
    - maildev
    environment:
      DJANGO_SETTINGS_MODULE: weblate.settings_docker
      WEBLATE_SITE_DOMAIN: ${WEBLATE_HOST}
      WEBLATE_EMAIL_HOST: maildev
      WEBLATE_EMAIL_PORT: 1025
      WEBLATE_EMAIL_USE_TLS: 0
      WEBLATE_EMAIL_USE_SSL: 0
    env_file:
    - ./environment
  database:
    image: postgres:17.4-alpine@sha256:7062a2109c4b51f3c792c7ea01e83ed12ef9a980886e3b3d380a7d2e5f6ce3f5
    env_file:
    - ./environment
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./postgres-init:/docker-entrypoint-initdb.d
    restart: always
    ports:
    - 5433:5432
  cache:
    image: redis:7.4.2-alpine@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
  maildev:
    image: maildev/maildev:2.2.1@sha256:180ef51f65eefebb0e7122d8308813c1fd7bff164bc440ce5a3c2feee167a810
    ports:
    - 1080:1080
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
