blank_issues_enabled: false
contact_links:
  - name: Docker image issue tracker
    url: https://github.com/WeblateOrg/docker/issues/
    about: For issues specific for Docker deployment.
  - name: translation-finder issue tracker
    url: https://github.com/WeblateOrg/translation-finder/issues/
    about: If this issue only involves translations discovery while importing, please open a new issue there.
  - name: wlc issue tracker
    url: https://github.com/WeblateOrg/wlc/issues/
    about: If this issue only involves command line client, please open a new issue there.
  - name: Paid support
    url: https://weblate.org/support/
    about: As the subscriber, you will always receive fast replies from our dedicated support team.
