version: "3"

services:
  database:
    image: mysql:8.0.26
    ports:
      - 60000:3306
    environment:
      MYSQL_ROOT_PASSWORD: weblate
  cache:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - 60001:6379
