name: Dependabot auto merge

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && ( github.event.label.name == 'python' || github.event.label.name == 'submodules' || github.event.label.name == 'docker' || github.event.label.name == 'github_actions' )
    steps:
      - name: Add merge comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "@dependabot merge"
