# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Documentation

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:
  schedule:
  - cron: 30 5 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  list-languages:
    runs-on: ubuntu-24.04
    outputs:
      languages: ${{ steps.list.outputs.languages }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
      with:
        enable-cache: false
        version: 0.9.10
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.14'
    - run: uv run --no-project scripts/list-documentation-languages.py >>"$GITHUB_OUTPUT"
      id: list

  translations:
    runs-on: ubuntu-24.04
    needs:
    - list-languages
    name: Sphinx
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.list-languages.outputs.languages) }}
    env:
      READTHEDOCS_LANGUAGE: ${{ matrix.language }}

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
      with:
        enable-cache: false
        version: 0.9.10
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.14'
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
    - name: Install Python dependencies
      run: uv sync --only-group docs --frozen
    - name: Sphinx build
      run: |
        . .venv/bin/activate
        echo "::add-matcher::.github/matchers/sphinx.json"
        ./ci/run-docs
        echo "::remove-matcher owner=sphinx::"
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: Documentation ${{ matrix.language }}
        path: docs/_build/html

  build:
    runs-on: ubuntu-24.04
    name: Sphinx
    needs:
    - translations
    steps:
    # This is dependency only job to collect all test results
    - run: echo
