# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Documentation

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:
  schedule:
  - cron: 30 5 * * *

permissions:
  contents: read

jobs:
  list-languages:
    runs-on: ubuntu-24.04
    outputs:
      languages: ${{ steps.list.outputs.languages }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - run: uv run --no-project scripts/list-documentation-languages.py >>"$GITHUB_OUTPUT"
      id: list

  translations:
    runs-on: ubuntu-24.04
    needs:
    - list-languages
    name: Sphinx
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.list-languages.outputs.languages) }}
    env:
      READTHEDOCS_LANGUAGE: ${{ matrix.language }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
    - name: Install Python dependencies
      run: uv sync --only-group docs --frozen
    - name: Sphinx build
      run: |
        . .venv/bin/activate
        echo "::add-matcher::.github/matchers/sphinx.json"
        ./ci/run-docs
        echo "::remove-matcher owner=sphinx::"
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: Documentation ${{ matrix.language }}
        path: docs/_build/html

  build:
    runs-on: ubuntu-24.04
    name: Sphinx
    needs:
    - translations
    steps:
    # This is dependency only job to collect all test results
    - run: echo
