name: Docs

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sphinx

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('**/requirements*.txt') }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.1.1
        with:
          python-version: 3.8
      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y graphviz
      - name: Install pip dependencies
        run: pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          echo "::add-matcher::.github/matchers/sphinx.json"
          ./ci/run-docs
          echo "::remove-matcher owner=sphinx::"
      - uses: actions/upload-artifact@v2.1.3
        with:
          name: Documentation
          path: docs/_build/html

  linkcheck:
    runs-on: ubuntu-latest
    name: Linkcheck

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('**/requirements*.txt') }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2.1.1
        with:
          python-version: 3.8
      - name: Install pip dependencies
        run: pip install -r docs/requirements.txt
      - name: Sphinx linkcheck
        run: |
          ./ci/run-docs linkcheck
      - name: Sphinx linkcheck collect
        if: always()
        run: |
          echo "::add-matcher::.github/matchers/sphinx-linkcheck.json"
          sed 's@^@docs/@' docs/_build/linkcheck/output.txt
          echo "::remove-matcher owner=sphinx::"
      - uses: actions/upload-artifact@v2.1.3
        if: always()
        with:
          name: Linkcheck report
          path: docs/_build/linkcheck/output.txt
