# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Documentation

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:
  schedule:
  - cron: 30 5 * * *

permissions:
  contents: read

jobs:
  list-languages:
    runs-on: ubuntu-24.04
    outputs:
      languages: ${{ steps.list.outputs.languages }}
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: uv run --no-project scripts/list-documentation-languages.py >>"$GITHUB_OUTPUT"
      id: list

  translations:
    runs-on: ubuntu-24.04
    needs:
    - list-languages
    name: Sphinx
    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJson(needs.list-languages.outputs.languages) }}
    env:
      READTHEDOCS_LANGUAGE: ${{ matrix.language }}

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
    - name: Install Python dependencies
      run: uv sync --no-sources --only-group docs --frozen
    - name: Sphinx build
      run: |
        . .venv/bin/activate
        echo "::add-matcher::.github/matchers/sphinx.json"
        ./ci/run-docs
        echo "::remove-matcher owner=sphinx::"
    - uses: actions/upload-artifact@v4.6.0
      with:
        name: Documentation ${{ matrix.language }}
        path: docs/_build/html

  build:
    runs-on: ubuntu-24.04
    name: Sphinx
    needs:
    - translations
    steps:
    # This is dependency only job to collect all test results
    - run: echo
