name: Docs

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    name: Sphinx

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-docs-${{ hashFiles('**/requirements*.txt') }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
    - name: Install pip dependencies
      run: pip install -r docs/requirements.txt
    - name: Sphinx build
      run: |
        echo "::add-matcher::.github/matchers/sphinx.json"
        ./ci/run-docs
        echo "::remove-matcher owner=sphinx::"
    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: docs/_build/html

  linkcheck:

    runs-on: ubuntu-latest
    name: Linkcheck

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-docs-${{ hashFiles('**/requirements*.txt') }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: pip install -r docs/requirements.txt
    - name: Sphinx linkcheck
      run: |
        echo "::add-matcher::.github/matchers/sphinx.json"
        ./ci/run-docs linkcheck
        echo "::remove-matcher owner=sphinx::"
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: Linkcheck report
        path: docs/_build/linkcheck/output.txt
