# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: FOSSA

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'WeblateOrg/weblate' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Run FOSSA Scan
      uses: fossas/fossa-action@93a52ecf7c3ac7eb40f5de77fd69b1a19524de94 # v1.5.0
      with:
        api-key: ${{secrets.fossaApiKey}}

    - name: Run FOSSA Test
      uses: fossas/fossa-action@93a52ecf7c3ac7eb40f5de77fd69b1a19524de94 # v1.5.0
      with:
        api-key: ${{secrets.fossaApiKey}}
        run-tests: true
