# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: FOSSA

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-slim
    if: ${{ github.repository == 'WeblateOrg/weblate' }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      with:
        persist-credentials: false
    - name: Run FOSSA Scan
      uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # v1.8.0
      with:
        api-key: ${{secrets.fossaApiKey}}

    - name: Run FOSSA Test
      uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # v1.8.0
      with:
        api-key: ${{secrets.fossaApiKey}}
        run-tests: true
