# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: 'Issues: Close stale'

on:
  schedule:
  - cron: 30 1 * * *
  push:
    branches:
    - main
    paths:
    - .github/workflows/issue-stale.yml

permissions:
  issues: write

jobs:
  stale-issues:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f # v10.0.0
      with:
        days-before-pr-stale: -1
        days-before-pr-close: -1
        days-before-stale: 14
        days-before-close: 5
        only-labels: 'Waiting for: Community'
        stale-issue-label: wontfix
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because there wasn’t any recent activity.

          It will be closed soon if no further action occurs.

          Thank you for your contributions!
