# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0
#
# Issue lifecycle: Add "Waiting for: Release" label when resolving an issue

name: 'Issues: Mark resolved issue'

on:
  issues:
    types: [closed]

permissions:
  contents: read

concurrency:
  # Avoid double execution as this can be triggered from commit and pull request
  # causing two closing events being delivered to the issue.
  group: ${{ github.workflow }}-${{ github.event.issue.id }}
  cancel-in-progress: true

jobs:
  apply-label:
    permissions:
      issues: write
    runs-on: ubuntu-24.04
    if: '! github.event.issue.pull_request'
    steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const labels = await github.rest.issues.listLabelsOnIssue({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          for (const label of labels.data) {
            if (label.name.startsWith('Waiting for: ')) {
              console.log(`Removing label ${label.name}`);
              await github.rest.issues.removeLabel({

                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
              })
            }
          }
          console.log(context.payload);
          if (context.payload.issue.state_reason == 'completed' && context.payload.issue.milestone && context.payload.issue.milestone.state == 'open') {
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Waiting for: Release']
            })
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
          Thank you for your report; the issue you have reported has just been resolved and
          the solution will be released in Weblate ${github.event.issue.milestone.title}.

          * In case you see a problem with the fix, please comment on this issue.
          * In case you see a similar problem, please open a separate issue.
          * If you are happy with the outcome, don’t hesitate to support Weblate by making a [donation](https://weblate.org/donate/).
          `
            })
          }
