# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: Issue labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issueLabeled:
    permissions:
      issues: write  # for peter-evans/create-or-update-comment to create or update comment
      pull-requests: write  # for peter-evans/create-or-update-comment to create or update comment
    runs-on: ubuntu-22.04
    steps:
    - name: Add backlog comment
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ github.event.label.name == 'backlog' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: >
          This issue has been added to the backlog. It is not scheduled
          on the Weblate roadmap, but it eventually might be implemented.


          In case you need this feature soon, please consider helping
          or push it by [funding the development](https://weblate.org/support/).
    - name: Add undecided comment
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ github.event.label.name == 'undecided' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: >
          This issue has been put aside. It is currently unclear if it will
          ever be implemented as it seems to cover too narrow of a use case
          or doesn't seem to fit into Weblate.


          Please try to clarify the use case or consider proposing something more generic to make it useful to more users.
    - name: Add question comment
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ github.event.label.name == 'question' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: >
          This issue has been marked as a question by a Weblate team member.
          Why? Because it belongs more to the professional [Weblate Care](https://care.weblate.org/)
          or community [Discussions](https://github.com/WeblateOrg/weblate/discussions) than here.
          We strive to answer these reasonably fast here, too, but
          [purchasing the support subscription](https://weblate.org/support/)
          is more responsible and faster for your business.
          And it makes Weblate stronger as well. Thanks!


          In case your question is already answered, [making a donation](https://weblate.org/donate/) is the right way to say thank you!
    - name: Add translate-toolkit comment
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ github.event.label.name == 'translate-toolkit' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: >
          The issue you've reported needs to be addressed in the [translate-toolkit](https://github.com/translate/translate/).
          Please file the issue there, and include links to any relevant specifications about the formats (if applicable).
    - name: Add good first issue comment
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ github.event.label.name == 'good first issue' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: >
          This issue seems to be a good fit for newbie contributors.
          You are welcome to contribute to Weblate! Don't hesitate to
          ask any questions you would have while implementing this.


          You can learn about how to get started in our
          [contributors documentation](https://docs.weblate.org/en/latest/contributing/index.html).
