# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: licenses update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/licenses-update.yml
    - scripts/generate-license-data.py
    - scripts/spdx-license-list

permissions:
  contents: read

jobs:
  licenses-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: true
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
    - run: ./scripts/generate-license-data.py
    - name: Update renovate branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
      with:
        commit_message: 'utils: Update SPDX license data'
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        branch: create-pull-request/licenses-update
        title: 'utils: Update SPDX license data'
        commit-message: 'utils: Update SPDX license data'
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies
