# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: licenses update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/licenses-update.yml
    - scripts/generate-license-data.py
    - scripts/spdx-license-list

permissions:
  contents: read

jobs:
  licenses-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - run: ./scripts/generate-license-data.py
    - name: Update renovate branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: 'utils: Update SPDX license data'
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        branch: create-pull-request/licenses-update
        title: 'utils: Update SPDX license data'
        commit-message: 'utils: Update SPDX license data'
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies
