# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: licenses update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/licenses-update.yml
    - scripts/generate-license-data.py
    - scripts/spdx-license-list

permissions:
  contents: read

jobs:
  licenses-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: true
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.14'
    - run: ./scripts/generate-license-data.py
    - name: Update renovate branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
      with:
        commit_message: 'utils: Update SPDX license data'
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
      with:
        branch: create-pull-request/licenses-update
        title: 'utils: Update SPDX license data'
        commit-message: 'utils: Update SPDX license data'
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies
