# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: licenses update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/licenses-update.yml
    - scripts/generate-license-data
    - scripts/spdx-license-list

permissions:
  contents: read

jobs:
  licenses-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: true
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
    - run: ./scripts/generate-license-data
    - name: Update renovate branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@3cc016cfc892e0844046da36fc68da4e525e081f # v6.0.0
      with:
        commit_message: 'utils: Update SPDX license data'
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        branch: create-pull-request/licenses-update
        title: 'utils: Update SPDX license data'
        commit-message: 'utils: Update SPDX license data'
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies
