name: licenses update

on:
  push:
    branches:
    - dependabot/**
    - deepsource-fix-**
    - renovate/**
    - main
    paths:
    - .github/workflows/licenses-update.yml
    - scripts/generate-license-data
    - scripts/spdx-license-list

jobs:
  licenses-update:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install black
    - run: ./scripts/generate-license-data
    - name: Update dependabot branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'utils: Update SPDX license data'
    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v4
      with:
        branch: create-pull-request/licenses-update
        title: 'utils: Update SPDX license data'
        commit-message: 'utils: Update SPDX license data'
        labels: |
          dependencies
          automerge
