# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Linkcheck

on:
  push:
    paths:
    - docs/**.rst
    - .github/workflows/linkcheck.yml
  pull_request:
    paths:
    - docs/**.rst
    - .github/workflows/linkcheck.yml
  schedule:
  - cron: 30 5 * * *

permissions:
  contents: read

jobs:
  linkcheck:
    runs-on: ubuntu-24.04
    name: Linkcheck

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'
    - uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6.3.0
    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt install -y graphviz
    - name: Install Python dependencies
      run: uv sync --only-group docs --frozen
    - name: Sphinx linkcheck
      run: |
        . .venv/bin/activate
        ./ci/run-docs linkcheck
    - name: Sphinx linkcheck collect
      if: always()
      run: |
        echo "::add-matcher::.github/matchers/sphinx-linkcheck.json"
        echo "::add-matcher::.github/matchers/sphinx-linkcheck-warn.json"
        sed 's@^@docs/@' docs/_build/linkcheck/output.txt
        echo "::remove-matcher owner=sphinx::"
        echo "::remove-matcher owner=sphinx-warn::"
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: Linkcheck report
        path: docs/_build/linkcheck/output.txt
