# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: macOS

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:

permissions:
  contents: read

jobs:
  macos:
    # This verifies that installation instructions works, any changes here
    # need to be reflected in docs/admin/install/venv-macos.rst
    runs-on: macos-15
    env:
      PYTHONUNBUFFERED: 1
      PYTHONWARNINGS: default,ignore:unclosed:ResourceWarning
    steps:
    - uses: actions/checkout@v4
    - run: brew update
    - run: brew upgrade
    - run: brew list --versions
    - run: brew deps --tree --installed
    - run: brew unlink pkg-config@0.29.2
      # Some images have pkg-config and some pkgconf, so ignore errors here
      continue-on-error: true
    - name: Install brew dependencies
      run: |
        brew install pango cairo gobject-introspection glib libyaml pkgconf zstd xxhash libxmlsec1 uv
    - name: Install Weblate
      run: |
        uv venv --python python3.12 .venv
        source .venv/bin/activate
        uv pip install -e ".[all]"
