# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: macOS

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:

permissions:
  contents: read

jobs:
  macos:
    # This verifies that installation instructions works, any changes here
    # need to be reflected in docs/admin/install/venv-macos.rst
    runs-on: macos-15
    env:
      PYTHONUNBUFFERED: 1
      PYTHONWARNINGS: default,ignore:unclosed:ResourceWarning
      CI_DATABASE: postgresql
      CI_REDIS_HOST: localhost
      CI_DB_HOST: localhost
      DJANGO_SETTINGS_MODULE: weblate.settings_test
      CI_SKIP_SAML: 1
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
    - run: brew update
    - run: brew upgrade
    - run: brew list --versions
    - run: brew deps --tree --installed
    - run: brew unlink pkg-config@0.29.2
      # Some images have pkg-config and some pkgconf, so ignore errors here
      continue-on-error: true
    - name: Install brew dependencies
      run: |
        brew install pango cairo gobject-introspection glib libyaml pkgconf zstd xxhash librsvg
    - name: Install test dependencies
      run: |
        brew install mysql icu4c redis postgresql
        brew link --force icu4c
    - name: Start services
      run: |
        brew services start postgresql
        brew services start redis
    - name: Install Weblate
      run: |
        uv venv --python python3.12 .venv
        source .venv/bin/activate
        uv pip install -e ".[all]"
    - name: Test with Django
      run: |
        # shellcheck disable=SC2155
        export CI_DB_USER="$(id -nu)"
        source .venv/bin/activate
        uv run --no-sources --all-extras pytest --junitxml=junit.xml --cov=weblate --numprocesses=auto weblate
    - uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
        name: Tests macos
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@f2dba722c67b86c6caa034178c6e4d35335f6706 # v1.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
