# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Migrations

on:
  push:
    branches-ignore:
    - deepsource-fix-**
    - renovate/**
    - weblate
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  migrations:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        database: [postgresql, mysql]
      fail-fast: false
    name: ${{ matrix.database }}
    env:
      CI_DATABASE: ${{ matrix.database }}
      CI_DB_PASSWORD: weblate
      CI_DB_HOST: 127.0.0.1
      CI_DB_PORT: '60000'
      CI_SELENIUM: '1'
      DJANGO_SETTINGS_MODULE: weblate.settings_test

    steps:
    - uses: actions/checkout@v3
    - name: Start services
      run: ./ci/services-up ${{ matrix.database }}
    - name: Install apt dependencies
      run: sudo ./ci/apt-install $CI_DATABASE
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
        cache: pip
        cache-dependency-path: '**/requirements*.txt'
    - name: Install pip dependencies
      run: |
        ./ci/pip-install migrations
    - name: Check missing migrations
      run: ./ci/run-checkmigrate
    - name: Migrate from 4.0
      run: ./ci/run-migrate 4.0
    - name: Migrate from 4.0.4
      run: ./ci/run-migrate 4.0.4
    - name: Migrate from 4.1
      run: ./ci/run-migrate 4.1
    - name: Migrate from 4.2
      run: ./ci/run-migrate 4.2
    - name: Migrate from 4.3
      run: ./ci/run-migrate 4.3
    - name: Migrate from 4.4
      run: ./ci/run-migrate 4.4
    - name: Migrate from 4.5
      run: ./ci/run-migrate 4.5
    - name: Migrate from 4.6
      run: ./ci/run-migrate 4.6
    - name: Migrate from 4.7
      run: ./ci/run-migrate 4.7
    - name: Migrate from 4.8
      run: ./ci/run-migrate 4.8
    - name: Migrate from 4.9
      run: ./ci/run-migrate 4.9
    - name: Migrate from 4.10
      run: ./ci/run-migrate 4.10
    - name: Migrate from 4.11
      run: ./ci/run-migrate 4.11
    - name: Migrate from 4.12
      run: ./ci/run-migrate 4.12
    - name: Migrate from 4.13
      run: ./ci/run-migrate 4.13
    - name: Migrate from 4.14
      run: ./ci/run-migrate 4.14
    - name: Migrate from 4.15
      run: ./ci/run-migrate 4.15
    - name: Migrate from 4.16
      run: ./ci/run-migrate 4.16
    - name: Coverage
      run: |
        coverage combine
        coverage xml
    - uses: codecov/codecov-action@v3.1.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: migrations
        name: Migrations ${{ matrix.database }}
    - name: Stop services
      if: always()
      run: ./ci/services-down ${{ matrix.database }}
