# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0
#
# Issue lifecycle: Remove "Waiting for: *" labels when closing a milestone

name: Milestone closed

on:
  milestone:
    types: [closed]

permissions:
  issues: write

jobs:
  apply-label:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: context.payload.milestone.number,
              state: 'closed',
          });

          console.log(`Fetched ${issues.length} issues.`);

          for (const issue of issues) {
            console.log(`Working on issue #${issue.number}...`);
            const labels = await github.rest.issues.listLabelsOnIssue({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            for (const label of labels.data) {
              if (label.name.startsWith('Waiting for: ')) {
                console.log(`Removing label ${label.name}`);
                await github.rest.issues.removeLabel({
                  issue_number: issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                })
              }
            }
          }
