# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: mypy

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 2
        persist-credentials: false
    - name: Get changed files
      if: github.event_name == 'pull_request'
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
      with:
        files: '**.py'
    - name: List all changed files
      if: github.event_name == 'pull_request'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        touch changed-files.txt
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file" >> changed-files.txt
        done
        cat changed-files.txt

    - name: Install apt dependencies
      run: sudo ./ci/apt-install
    - uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      with:
        enable-cache: true
        cache-dependency-glob: ''
        cache-suffix: '3.13'
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'

    - name: Run mypy
      env:
        CI_DATABASE: postgresql
      run: uv run --all-extras --group types mypy --show-column-numbers weblate scripts/*.py > mypy.log
      # Temporary hack until we have this fully working
      continue-on-error: true
    - name: Report mypy
      if: always()
      run: |
        echo "::add-matcher::.github/matchers/mypy.json"
        if [ -f changed-files.txt ] ; then
          if grep --silent --fixed-strings --file=changed-files.txt mypy.log ; then
            grep --fixed-strings --file=changed-files.txt mypy.log
          fi
        else
          cat mypy.log
        fi
        echo "::remove-matcher owner=mypy::"
