# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: mypy

on:
  push:
    branches-ignore:
    - renovate/**
    - weblate
  pull_request:

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 2
    - name: Get changed files
      if: github.event_name == 'pull_request'
      id: changed-files
      uses: tj-actions/changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b # v45.0.8
      with:
        files: '**.py'
    - name: List all changed files
      if: github.event_name == 'pull_request'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        touch changed-files.txt
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file" >> changed-files.txt
        done
        cat changed-files.txt

    - name: Install apt dependencies
      run: sudo ./ci/apt-install
    - uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
      with:
        enable-cache: true
        cache-dependency-glob: ''
        cache-suffix: '3.13'
    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.13'

    - name: Run mypy
      run: uv run --no-sources --all-extras --group types mypy --show-column-numbers weblate > mypy.log
      # Temporary hack until we have this fully working
      continue-on-error: true
    - name: Report mypy
      if: always()
      run: |
        echo "::add-matcher::.github/matchers/mypy.json"
        if [ -f changed-files.txt ] ; then
          if grep --silent --fixed-strings --file=changed-files.txt mypy.log ; then
            grep --fixed-strings --file=changed-files.txt mypy.log
          fi
        else
          cat mypy.log
        fi
        echo "::remove-matcher owner=mypy::"
