# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/

name: Pull request automation

on:
  pull_request_target:
    types: opened

permissions:
  contents: read

jobs:
  weblate_automerge:
    permissions:
      pull-requests: write # for actions-ecosystem/action-add-labels to add label
    runs-on: ubuntu-20.04
    name: Weblate automerge
    if: ${{ github.actor == 'weblate' || github.actor == 'pre-commit-ci[bot]' }}
    steps:
    - uses: actions-ecosystem/action-add-labels@v1.1.3
      with:
        labels: automerge
