# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/

name: Pull request automation

on:
  pull_request_target:
    types: opened

permissions:
  contents: read

jobs:
  weblate_automerge:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Weblate automerge
    if: github.actor == 'weblate'
    steps:
    - uses: peter-evans/enable-pull-request-automerge@v2
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: rebase
