# This file is maintained in https://github.com/WeblateOrg/meta/

name: Pull request automation

on:
  pull_request_target:
    types: opened

jobs:
  weblate_automerge:
    runs-on: ubuntu-20.04
    name: Weblate automerge
    if: github.actor == 'weblate' || github.actor == 'pre-commit-ci'
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
