# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: jsonschema update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/schema-update.yml
    - pyproject.toml
    - docs/Makefile

permissions:
  contents: read

jobs:
  jsonschema-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
      with:
        enable-cache: false
        version: 0.9.9
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.14'
    - name: Install Python dependencies
      run: |
        uv sync --only-group schemas --only-group pre-commit
    - run: make -C docs update-schemas
    - run: uv run --only-group pre-commit pre-commit run --all
      continue-on-error: true

    - run: git diff

    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: github.event_name == 'pull_request' && github.actor != 'renovate[bot]'
      with:
        msg: 'docs: Update JSON schemas'

    - name: Update current branch
      if: github.event_name == 'push' && github.ref_name != 'main'
      uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
      with:
        commit_message: 'docs: Update JSON schemas'

    - name: Create Pull Request
      id: cpr
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref_name == 'main'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        branch: create-pull-request/jsonschema-update
        title: 'docs: Update JSON schemas'
        commit-message: 'docs: Update JSON schemas'

        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies

    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation && steps.cpr.outputs.pull-request-operation != 'none'
      run: gh pr merge --rebase --auto "$PR_NUMBER"
      env:
        GH_TOKEN: ${{ secrets.WEBLATE_CI_TOKEN }}
        PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
