# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: jsonschema update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/schema-update.yml
    - pyproject.toml
    - docs/Makefile

permissions:
  contents: read

jobs:
  jsonschema-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
    - uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5
    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
      with:
        python-version: '3.13'
    - name: Install Python dependencies
      run: |
        # shellcheck disable=SC2046
        uv pip install --system $(sed -n 's/.*"\(weblate-schemas==\([^"]*\)\)".*/\1/p' pyproject.toml)
        # shellcheck disable=SC2046
        uv pip install --system $(sed -n 's/.*"\(pre-commit==\([^"]*\)\)".*/\1/p' pyproject.toml)
    - run: make -C docs update-schemas
    - run: |
        # shellcheck disable=SC2046
        pre-commit run --files $(git diff --name-only)
      continue-on-error: true
    - name: Update renovate branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
      with:
        commit_message: 'docs: Update JSON schemas'
    - name: Create Pull Request
      id: cpr
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
      with:
        branch: create-pull-request/jsonschema-update
        title: 'docs: Update JSON schemas'
        commit-message: 'docs: Update JSON schemas'
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies

    - name: Enable Pull Request Automerge
      if: github.ref == 'refs/heads/main' && steps.cpr.outputs.pull-request-operation != 'none'
      run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.WEBLATE_CI_TOKEN }}
