# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: jsonschema update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/schema-update.yml
    - pyproject.toml
    - docs/Makefile

permissions:
  contents: read

jobs:
  jsonschema-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      if: github.event_name != 'pull_request' && github.repository_owner == 'WeblateOrg'
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      if: github.event_name != 'pull_request' && github.repository_owner != 'WeblateOrg'
      with:
        persist-credentials: true
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      if: github.event_name == 'pull_request'
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
      with:
        enable-cache: false
        version: 0.10.6
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - name: Install Python dependencies
      run: |
        uv sync --only-group schemas --only-group pre-commit
    - run: make -C docs update-schemas

    - name: Commit or create pull request
      uses: ./.github/actions/auto-commit
      with:
        message: 'docs: Update JSON schemas'
        pr-branch: create-pull-request/jsonschema-update
        pr-labels: |
          dependencies
        github-token: ${{ secrets.WEBLATE_CI_TOKEN }}
