# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: jsonschema update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/schema-update.yml
    - pyproject.toml
    - docs/Makefile

permissions:
  contents: read

jobs:
  jsonschema-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
      with:
        enable-cache: false
        version: 0.9.29
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - name: Install Python dependencies
      run: |
        uv sync --only-group schemas --only-group pre-commit
    - run: make -C docs update-schemas
    - run: uv run --frozen --only-group pre-commit prek run --all-files
      continue-on-error: true

    - run: git diff

    - name: Commit or create pull request
      uses: ./.github/actions/auto-commit
      with:
        message: 'docs: Update JSON schemas'
        pr-branch: create-pull-request/jsonschema-update
        pr-labels: |
          dependencies
        github-token: ${{ secrets.WEBLATE_CI_TOKEN }}
