# This file is maintained in https://github.com/WeblateOrg/meta/
name: Close stale

on:
  schedule:
  - cron: 30 1 * * *
  push:
    branches:
    - main
    paths:
    - .github/workflows/stale.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale-issues:
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v7
      with:
        days-before-pr-stale: 30
        days-before-pr-close: 14
        days-before-stale: 10
        days-before-close: 4
        exempt-issue-labels: bug,enhancement,documentation,security
        stale-issue-label: wontfix
        stale-pr-label: wontfix
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because there wasn’t any recent activity.

          It will be closed soon if no further action occurs.

          Thank you for your contributions!
        stale-pr-message: |
          This pull request has been automatically marked as stale because there wasn’t any recent activity.

          It will be closed soon if no further action occurs.

          Thank you for your contributions!
