# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: unicodechars update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/unicodechars.yml
    - scripts/generate-unicodechars.py
  workflow_dispatch:
  pull_request:
    paths:
    - .github/workflows/unicodechars.yml
    - scripts/generate-unicodechars.py

permissions:
  contents: read

jobs:
  unicodechars-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      if: github.event_name != 'pull_request'
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      if: github.event_name == 'pull_request'
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      with:
        enable-cache: false
        version: 0.9.26
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
    - name: Install Python dependencies
      run: uv sync --only-group pre-commit
    - run: ./scripts/generate-unicodechars.py > weblate/utils/unicodechars.py
    - run: uv run --only-group pre-commit pre-commit run --all
      continue-on-error: true

    - run: git diff

    - name: Commit or create pull request
      uses: ./.github/actions/auto-commit
      with:
        message: 'chore: update unicode characters data'
        pr-branch: create-pull-request/jsonschema-update
        pr-labels: |
          dependencies
        github-token: ${{ secrets.WEBLATE_CI_TOKEN }}
