# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: uv lock update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - pyproject.toml
    - .github/workflows/uv-upgrade.yml
  schedule:
  - cron: 30 6 * * 0
  workflow_dispatch:
  pull_request:
    paths:
    - pyproject.toml
    - .github/workflows/uv-upgrade.yml

permissions:
  contents: write

jobs:
  uv-update:
    if: startsWith(github.repository, 'WeblateOrg/')
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: github.event_name != 'pull_request'
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: github.event_name == 'pull_request'
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
      with:
        enable-cache: true
        cache-dependency-glob: ''
        cache-suffix: '3.13'

    - name: Install apt dependencies
      run: |
        if [ -f ./ci/apt-install ] ; then
          sudo ./ci/apt-install
        fi

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13'

    - name: Lockfile maintenance
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: uv lock --upgrade

    - run: uv sync --all-extras
      if: hashFiles('uv.lock') != ''

    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: github.event_name == 'pull_request' && github.actor != 'renovate[bot]'
      with:
        msg: 'chore(deps): update lockfile'

    - name: Update current branch
      if: github.event_name == 'push' && github.ref_name != 'main'
      uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
      with:
        commit_message: 'chore(deps): update lockfile'

    - name: Create Pull Request
      id: cpr
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        branch: create-pull-request/uv-lock-update
        title: 'chore(deps): update lockfile'
        commit-message: 'chore(deps): update lockfile'

        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies

    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation && steps.cpr.outputs.pull-request-operation != 'none'
      run: gh pr merge --rebase --auto "$PR_NUMBER"
      env:
        GH_TOKEN: ${{ secrets.WEBLATE_CI_TOKEN }}
        PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
