# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: yarn update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/yarn-update.yml
    - scripts/yarn-update
    - scripts/yarn/*
    - client/*
  schedule:
  - cron: 30 5 * * 0
  workflow_dispatch:
  pull_request:
    paths:
    - .github/workflows/yarn-update.yml
    - scripts/yarn-update
    - scripts/yarn/*
    - client/*

permissions:
  contents: read

jobs:
  yarn-update:
    permissions:
      contents: write
    if: startsWith(github.repository, 'WeblateOrg/')
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      if: github.event_name != 'pull_request'
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        persist-credentials: true
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      if: github.event_name == 'pull_request'
      with:
        persist-credentials: false
    - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      with:
        enable-cache: false

        version: 0.9.26
    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.14'
    - name: Lockfile maintenance
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: |
        for dir in scripts/yarn client ; do
          if [ ! -d $dir ] ; then
            echo "Skipping $dir"
            continue
          fi
          pushd "$dir"
          yarn upgrade
          popd
        done

    - run: ./scripts/yarn-update
      if: hashFiles('scripts/yarn-update') != ''

    - run: |
        if [ -d client ] ; then
          cd client
          yarn install --check-files
          yarn build
          cd ..
        fi

    - name: Update SBOM
      if: hashFiles('docs/specs/sbom/partial/javascript.json') != ''
      working-directory: ./client
      run: |
        npm sbom --omit dev --sbom-format cyclonedx --sbom-type application > ../docs/specs/sbom/partial/javascript.json
        ../scripts/reproducible-sbom.py ../docs/specs/sbom/partial/javascript.json

    - name: Merge SBOM
      if: hashFiles('docs/specs/sbom/partial/python.json') != ''
      env:
        # renovate: datasource=github-releases depName=CycloneDX/cyclonedx-cli versioning=loose
        CYCLONEDX_CLI_VERSION: v0.29.2
      run: |
        curl -L "https://github.com/CycloneDX/cyclonedx-cli/releases/download/$CYCLONEDX_CLI_VERSION/cyclonedx-linux-x64" > /tmp/cyclonedx-linux-x64
        chmod +x /tmp/cyclonedx-linux-x64
        /tmp/cyclonedx-linux-x64 merge --input-files docs/specs/sbom/partial/* --output-file docs/specs/sbom/sbom.json
        ./scripts/reproducible-sbom.py docs/specs/sbom/sbom.json

    - run: uv run --only-group pre-commit pre-commit run --all
      continue-on-error: true

    - run: git diff

    - name: Commit or create pull request
      uses: ./.github/actions/auto-commit
      with:
        message: 'chore(js): update vendored libraries'
        pr-branch: create-pull-request/yarn-update
        pr-labels: |
          dependencies
        github-token: ${{ secrets.WEBLATE_CI_TOKEN }}
