# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/WeblateOrg/meta/
name: yarn update

on:
  push:
    branches:
    - renovate/**
    - main
    paths:
    - .github/workflows/yarn-update.yml
    - scripts/yarn-update
    - scripts/yarn/*
    - client/*
  schedule:
  - cron: 30 5 * * 0
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yarn-update:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683                                       # v4
      with:
        token: ${{ secrets.WEBLATE_CI_TOKEN }}

    - name: Lockfile maintenance
      if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      run: |
        for dir in scripts/yarn client ; do
          if [ ! -d $dir ] ; then
            echo "Skipping $dir"
            continue
          fi
          pushd "$dir"
          yarn upgrade
          popd
        done

    - run: ./scripts/yarn-update
      if: hashFiles('scripts/yarn-update') != ''

    - run: |
        if [ -d client ] ; then
          cd client
          yarn install --check-files
          yarn build
          cd ..
        fi

    - name: Update current branch
      if: github.ref != 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
      with:
        commit_message: 'chore(js): update vendored libraries'

    - name: Create Pull Request
      id: cpr
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
      with:
        branch: create-pull-request/yarn-update
        title: 'chore(js): update vendored libraries'
        commit-message: 'chore(js): update vendored libraries'

        token: ${{ secrets.WEBLATE_CI_TOKEN }}
        labels: |
          dependencies

    - name: Enable Pull Request Automerge
      if: github.ref == 'refs/heads/main' && steps.cpr.outputs.pull-request-operation != 'none'
      run: gh pr merge --rebase --auto "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.WEBLATE_CI_TOKEN }}
